// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example_service.proto

#include "example_service.pb.h"
#include "example_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace examples_service {

static const char* Greeter_method_names[] = {
  "/examples_service.Greeter/SayHello",
  "/examples_service.Greeter/LotsOfReplies",
  "/examples_service.Greeter/LotsOfGreetings",
  "/examples_service.Greeter/BidiHello",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel, options));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_LotsOfReplies_(Greeter_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_LotsOfGreetings_(Greeter_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_BidiHello_(Greeter_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::examples_service::HelloRequest& request, ::examples_service::HelloResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::examples_service::HelloRequest, ::examples_service::HelloResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::examples_service::HelloRequest* request, ::examples_service::HelloResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::examples_service::HelloRequest, ::examples_service::HelloResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, std::move(f));
}

void Greeter::Stub::async::SayHello(::grpc::ClientContext* context, const ::examples_service::HelloRequest* request, ::examples_service::HelloResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SayHello_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::examples_service::HelloResponse>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::examples_service::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::examples_service::HelloResponse, ::examples_service::HelloRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SayHello_, context, request);
}

::grpc::ClientAsyncResponseReader< ::examples_service::HelloResponse>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::examples_service::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSayHelloRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::examples_service::HelloResponse>* Greeter::Stub::LotsOfRepliesRaw(::grpc::ClientContext* context, const ::examples_service::HelloRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::examples_service::HelloResponse>::Create(channel_.get(), rpcmethod_LotsOfReplies_, context, request);
}

void Greeter::Stub::async::LotsOfReplies(::grpc::ClientContext* context, const ::examples_service::HelloRequest* request, ::grpc::ClientReadReactor< ::examples_service::HelloResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::examples_service::HelloResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_LotsOfReplies_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::examples_service::HelloResponse>* Greeter::Stub::AsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::examples_service::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::examples_service::HelloResponse>::Create(channel_.get(), cq, rpcmethod_LotsOfReplies_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::examples_service::HelloResponse>* Greeter::Stub::PrepareAsyncLotsOfRepliesRaw(::grpc::ClientContext* context, const ::examples_service::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::examples_service::HelloResponse>::Create(channel_.get(), cq, rpcmethod_LotsOfReplies_, context, request, false, nullptr);
}

::grpc::ClientReaderWriter< ::examples_service::HelloRequest, ::examples_service::HelloResponse>* Greeter::Stub::LotsOfGreetingsRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::examples_service::HelloRequest, ::examples_service::HelloResponse>::Create(channel_.get(), rpcmethod_LotsOfGreetings_, context);
}

void Greeter::Stub::async::LotsOfGreetings(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::examples_service::HelloRequest,::examples_service::HelloResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::examples_service::HelloRequest,::examples_service::HelloResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_LotsOfGreetings_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::examples_service::HelloRequest, ::examples_service::HelloResponse>* Greeter::Stub::AsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::examples_service::HelloRequest, ::examples_service::HelloResponse>::Create(channel_.get(), cq, rpcmethod_LotsOfGreetings_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::examples_service::HelloRequest, ::examples_service::HelloResponse>* Greeter::Stub::PrepareAsyncLotsOfGreetingsRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::examples_service::HelloRequest, ::examples_service::HelloResponse>::Create(channel_.get(), cq, rpcmethod_LotsOfGreetings_, context, false, nullptr);
}

::grpc::ClientReaderWriter< ::examples_service::HelloRequest, ::examples_service::HelloResponse>* Greeter::Stub::BidiHelloRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::examples_service::HelloRequest, ::examples_service::HelloResponse>::Create(channel_.get(), rpcmethod_BidiHello_, context);
}

void Greeter::Stub::async::BidiHello(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::examples_service::HelloRequest,::examples_service::HelloResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::examples_service::HelloRequest,::examples_service::HelloResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_BidiHello_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::examples_service::HelloRequest, ::examples_service::HelloResponse>* Greeter::Stub::AsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::examples_service::HelloRequest, ::examples_service::HelloResponse>::Create(channel_.get(), cq, rpcmethod_BidiHello_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::examples_service::HelloRequest, ::examples_service::HelloResponse>* Greeter::Stub::PrepareAsyncBidiHelloRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::examples_service::HelloRequest, ::examples_service::HelloResponse>::Create(channel_.get(), cq, rpcmethod_BidiHello_, context, false, nullptr);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::examples_service::HelloRequest, ::examples_service::HelloResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::examples_service::HelloRequest* req,
             ::examples_service::HelloResponse* resp) {
               return service->SayHello(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Greeter::Service, ::examples_service::HelloRequest, ::examples_service::HelloResponse>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             const ::examples_service::HelloRequest* req,
             ::grpc::ServerWriter<::examples_service::HelloResponse>* writer) {
               return service->LotsOfReplies(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Greeter::Service, ::examples_service::HelloRequest, ::examples_service::HelloResponse>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::examples_service::HelloResponse,
             ::examples_service::HelloRequest>* stream) {
               return service->LotsOfGreetings(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[3],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Greeter::Service, ::examples_service::HelloRequest, ::examples_service::HelloResponse>(
          [](Greeter::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::examples_service::HelloResponse,
             ::examples_service::HelloRequest>* stream) {
               return service->BidiHello(ctx, stream);
             }, this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::examples_service::HelloRequest* request, ::examples_service::HelloResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::LotsOfReplies(::grpc::ServerContext* context, const ::examples_service::HelloRequest* request, ::grpc::ServerWriter< ::examples_service::HelloResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::LotsOfGreetings(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::examples_service::HelloResponse, ::examples_service::HelloRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::BidiHello(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::examples_service::HelloResponse, ::examples_service::HelloRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace examples_service

